http:
  port: "8081"

ws-host: "diy-api-20201209.us-w2.cloudhub.io"
queue-name: "accounts"

soap_ws:
  wsdl: "http://apdev-accounts-ws.cloudhub.io/api/transactions?wsdl"
  service: "TransactionServiceService"
  port: "TransactionServicePort"
  address: "http://apdev-accounts-ws.cloudhub.io/api/transactions"
  
# Accounts
accounts:
  host: "diy-api-20201209.us-w2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "39100c46cff946b5868874321cb173c8"
  client_secret: "ff038c1977E04804aC16bbE0Af89cf12"